# Change these first
owner: pmh-only # Your GitHub organization or username, where this repository lives
repo: pmhserver-status # The name of this repository

sites:
  - name: pmhserver - Website
    url: https://shutupandtakemy.codes
    maxResponseTime: 3000
    icon: https://shutupandtakemy.codes/mntserver.png
  - name: pmhserver - Minecraft
    check: "tcp-ping"
    url: shutupandtakemy.codes
    port: 25565
    icon: https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon.ico
  - name: Cloudflare
    check: "tcp-ping"
    url: jack.ns.cloudflare.com
    port: 53
    icon: https://cloudflare.com/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.shutupandtakemy.codes
  theme: night
  # baseUrl: /your-repo-name
  favicon: https://shutupandtakemy.codes/mntserver.png
  logoUrl: https://shutupandtakemy.codes/mntserver.png
  name: pmhserver
  introTitle: "**pmhserver** is the open-infra homelab server for personal purpose."
  introMessage: You can view pmhserver's infrastructure files (Caddyfile, docker-compose.yml etc...) in [Github Repo](https://github.com/pmh-only/composes).
  navbar:
    - title: Home
      href: https://shutupandtakemy.codes
    - title: Minecraft
      href: https://mc.shutupandtakemy.codes
    - title: Graph
      href: https://shutupandtakemy.codes/#netgraph
    - title: Monitor
      href: https://grafana.shutupandtakemy.codes
    - title: Status
      href: /

assignees:
  - pmh-only

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
