# Change these first
owner: pmh-only # Your GitHub organization or username, where this repository lives
repo: pmhserver-status # The name of this repository

sites:
  - name: pmhserver
    url: https://shutupandtakemy.codes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.shutupandtakemy.codes
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: pmhserver
  introTitle: "**pmhserver** is the open-infra homelab server for personal purpose."
  introMessage: You can view pmhserver's infrastructure files (Caddyfile, docker-compose.yml etc...) in [Github Repo](https://github.com/pmh-only/composes).
  navbar:
    - title: Status
      href: /
    - title: Composes
      href: https://github.com/pmh-only/composes

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
